// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaubfpXKUtWbaFoAy2Wrji0A0KEAXlkY',
    appId: '1:188476409125:web:f18745c76d3a5d596a46cc',
    messagingSenderId: '188476409125',
    projectId: 'volunegy',
    authDomain: 'volunegy.firebaseapp.com',
    storageBucket: 'volunegy.appspot.com',
    measurementId: 'G-PRKSTQ2BCL',
    databaseURL:
        "https://volunegy-default-rtdb.europe-west1.firebasedatabase.app/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwFz-1-Nyt_oQjS_tjQWZfJIBv4n6vlI',
    appId: '1:188476409125:android:bae59b8620d1cfc86a46cc',
    messagingSenderId: '188476409125',
    projectId: 'volunegy',
    storageBucket: 'volunegy.appspot.com',
    databaseURL:
        "https://volunegy-default-rtdb.europe-west1.firebasedatabase.app/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCbq6eqtxOUGBcUqWA6gNdWH4374GO7E',
    appId: '1:188476409125:ios:ca8f1c10cf90f3926a46cc',
    messagingSenderId: '188476409125',
    projectId: 'volunegy',
    storageBucket: 'volunegy.appspot.com',
    iosClientId:
        '188476409125-k7huqho9vlt11sjn0b45p0pu0j9tdomj.apps.googleusercontent.com',
    iosBundleId: 'com.example.volun',
    databaseURL:
        "https://volunegy-default-rtdb.europe-west1.firebasedatabase.app/",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCCbq6eqtxOUGBcUqWA6gNdWH4374GO7E',
    appId: '1:188476409125:ios:ca8f1c10cf90f3926a46cc',
    messagingSenderId: '188476409125',
    projectId: 'volunegy',
    storageBucket: 'volunegy.appspot.com',
    iosClientId:
        '188476409125-k7huqho9vlt11sjn0b45p0pu0j9tdomj.apps.googleusercontent.com',
    iosBundleId: 'com.example.volun',
    databaseURL:
        "https://volunegy-default-rtdb.europe-west1.firebasedatabase.app/",
  );
}
